[project]
name = "annual-rainfall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "numpy>=2.3.3",
    "openmeteo-requests>=1.7.2",
    "pandas>=2.3.2",
    "requests-cache<1.2",
    "retry-requests>=2.0.0",
    "urllib3<2",
    "uvicorn>=0.35.0",
]
